<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <UserSecretsId>a2a8c4b2-6c7a-4596-bca6-60a6cecccff4</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Otus.ToDoList.ConsoleBot\Otus.ToDoList.ConsoleBot.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Core\Exceptions\" />
    </ItemGroup>

</Project>
